pipelines:
  group: defaultGroup

pipeline:
  name: gocd
  materials:
    - git:
        url: https://github.com/magnus-lycka/gocd.git
        dest: gocd
  template: my_template
  params:
    - PARAM_NAME1: param value 1
    - PARAM_NAME2: param value 2
  environmentvariables:
    - ENV_NAME1: env value 1
    - ENV_NAME2: env value 2

environment: blue_environment