pipelines:
  group: defaultGroup

pipeline:
  name: {{ name }}
  materials:
    - git:
        url: {{ url }}
        {% if not skip_dest %}dest: {{ dest or name }}{% endif %}
  stages:
    - stage:
        name: defaultStage
        jobs:
          - job:
              name: defaultJob
              tasks:
                - exec:
                    command: /bin/bash
                    workingdir: gocd
                    arg:
                      - -c
                      - echo $SHELL $GO_PIPELINE_LABEL
