pipelines:
  group: defaultGroup

pipeline:
  name: gocd
  materials:
    - git:
        url: https://github.com/magnus-lycka/gocd.git
        dest: gocd
  stages:
    - stage:
        name: defaultStage
        jobs:
          - job:
              name: defaultJob
              tasks:
                - exec:
                    command: /bin/bash
                    workingdir: gocd
                    arg:
                      - -c
                      - echo $SHELL $GO_PIPELINE_LABEL

environment: blue_environment
